[colors]
[colors.primary]
background = "#222235"
foreground = "#B8B7CB"

[colors.normal]
black   = "#222235"
red     = "#b68588"
green   = "#69977d"
yellow  = "#78956b"
blue    = "#8691bd"
magenta = "#a588ab"
cyan    = "#70a8b1"
white   = "#B8B7CB"

[colors.bright]
black   = "#74747b"
red     = "#e1a8ac"
green   = "#89be9c"
yellow  = "#99bc84"
blue    = "#aab5ed"
magenta = "#ba93c2"
cyan    = "#6bbbc7"
white   = "#c9c8d0"

[colors.cursor]
text   = "#222235"
cursor = "#B8B7CB"
