# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#222235"

# Main text color
theme[main_fg]="#B8B7CB"

# Title color for boxes
theme[title]="#B8B7CB"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#8691bd"

# Background color of selected item in processes box
theme[selected_bg]="#B8B7CB"

# Foreground color of selected item in processes box
theme[selected_fg]="#8691bd"

# Color of inactive/disabled text
theme[inactive_fg]="#74747b"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#c3c2d3"

# Background color of the percentage meters
theme[meter_bg]="#B8B7CB"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#c3c2d3"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#a588ab"
theme[mem_box]="#69977d"
theme[net_box]="#b68588"
theme[proc_box]="#8691bd"

# Box divider line and small boxes line color
theme[div_line]="#74747b"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#69977d"
theme[temp_mid]="#78956b"
theme[temp_end]="#b68588"

# CPU graph colors (Teal -> Blue -> Purple)
theme[cpu_start]="#70a8b1"
theme[cpu_mid]="#8691bd"
theme[cpu_end]="#a588ab"

# Mem/Disk free meter
theme[free_start]="#a588ab"
theme[free_mid]="#8691bd"
theme[free_end]="#70a8b1"

# Mem/Disk cached meter
theme[cached_start]="#8691bd"
theme[cached_mid]="#70a8b1"
theme[cached_end]="#a588ab"

# Mem/Disk available meter
theme[available_start]="#78956b"
theme[available_mid]="#b68588"
theme[available_end]="#b68588"

# Mem/Disk used meter (Green -> Teal -> Blue)
theme[used_start]="#69977d"
theme[used_mid]="#70a8b1"
theme[used_end]="#8691bd"

# Download graph colors
theme[download_start]="#78956b"
theme[download_mid]="#b68588"
theme[download_end]="#b68588"

# Upload graph colors (Green -> Teal -> Blue)
theme[upload_start]="#69977d"
theme[upload_mid]="#70a8b1"
theme[upload_end]="#8691bd"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#70a8b1"
theme[process_mid]="#8691bd"
theme[process_end]="#a588ab"

# Graph gradient colors (spectrum shades from background to foreground)
theme[gradient_color_0]="#222235"
theme[gradient_color_1]="#383849"
theme[gradient_color_2]="#B8B7CB"
theme[gradient_color_3]="#74747b"
theme[gradient_color_4]="#8a8998"
theme[gradient_color_5]="#B8B7CB"
theme[gradient_color_6]="#c3c2d3"
theme[gradient_color_7]="#cac9d8"
