# UI Colors (extended)
accent = "#8691bd"
cursor = "#B8B7CB"

# Primary colors
foreground = "#B8B7CB"
background = "#222235"

# Selection colors
selection_foreground = "#222235"
selection_background = "#B8B7CB"

# Normal colors (ANSI 0-7)
color0 = "#222235"
color1 = "#b68588"
color2 = "#69977d"
color3 = "#78956b"
color4 = "#8691bd"
color5 = "#a588ab"
color6 = "#70a8b1"
color7 = "#B8B7CB"

# Bright colors (ANSI 8-15)
color8 = "#74747b"
color9 = "#e1a8ac"
color10 = "#89be9c"
color11 = "#99bc84"
color12 = "#aab5ed"
color13 = "#ba93c2"
color14 = "#6bbbc7"
color15 = "#c9c8d0"
