# Background and foreground colors
background = #222235
foreground = #B8B7CB

# Standard colors
palette = 0=#222235
palette = 1=#b68588
palette = 2=#69977d
palette = 3=#78956b
palette = 4=#8691bd
palette = 5=#a588ab
palette = 6=#70a8b1
palette = 7=#B8B7CB

# Bright colors
palette = 8=#74747b
palette = 9=#e1a8ac
palette = 10=#89be9c
palette = 11=#99bc84
palette = 12=#aab5ed
palette = 13=#ba93c2
palette = 14=#6bbbc7
palette = 15=#c9c8d0
