$color = rgba(34, 34, 53, 1)
$inner_color = rgba(34, 34, 53, 0.66)
$outer_color = rgba(165, 136, 171, 1)
$font_color = rgba(184, 183, 203, 1)
$font_color_alpha = B8B7CB
$placeholder_color = rgba(184, 183, 203, 0.7)
$check_color = rgba(112, 168, 177, 1)
$accent = 8691bd
