background            #222235
foreground            #B8B7CB

# black
color0  #222235
color8  #74747b

# red
color1  #b68588
color9  #e1a8ac

# green
color2  #69977d
color10 #89be9c

# yellow
color3  #78956b
color11 #99bc84

# blue
color4  #8691bd
color12 #aab5ed

# magenta
color5  #a588ab
color13 #ba93c2

#cyan
color6  #70a8b1
color14 #6bbbc7

#white
color7  #B8B7CB
color15 #c9c8d0


