
#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:



# Start Polkit
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1


exec-once = $terminal
exec-once = nm-applet &
exec-once = waybar & hyprpaper & $browser & hypridle
exec-once = system --user start hyprpolkitagent

### Copy and paste
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
