source = $HOME/.config/aether/theme/hyprlock.conf

$font = JetBrainsMono Nerd Font

# GENERAL
general {
    disable_loading_bar = true
    hide_cursor = true
    ignore_empty_input = true
}

# BACKGROUND
background {
    monitor =
    path = ~/.config/aether/theme/backgrounds/shaded.png
    blur_passes = 2
    color = $color
}

# TIME
label {
    monitor =
    text = cmd[update:30000] echo "$(date +"%R")"
    color = $font_color
    font_size = 90
    font_family = $font
    position = -30, 0
    halign = right
    valign = top
}

# DATE 
label {
    monitor = 
    text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
    color = $font_color
    font_size = 25
    font_family = $font
    position = -30, -150
    halign = right
    valign = top
}

# USER AVATAR

image {
    monitor = 
    path = ~/.face
    size = 100
    border_color = $outer_color

    position = 0, 75
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $outer_color
    inner_color = $inner_color
    font_color = $font_color
    fade_on_empty = false
    placeholder_text = <span foreground="##$font_color_alpha"><i>󰌾 Logged in as </i><span foreground="##$accent">$USER</span></span>
    hide_input = false
    check_color = $check_color
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $yellow
    position = 0, -35
    halign = center
    valign = center
}
