$color = {background.rgba}
$inner_color = {background.rgba:0.66}
$outer_color = {magenta.rgba}
$font_color = {foreground.rgba}
$font_color_alpha = {foreground.strip}
$placeholder_color = {foreground.rgba:0.7}
$check_color = {cyan.rgba}
$accent = {accent.strip}
