# BEGIN_KITTY_THEME
include $HOME/.config/aether/theme/kitty.conf
# END_KITTY_THEME
#
font_family JetBrainsMono Nerd Font
# font_family CaskaydiaCove Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 11

# Window
window_padding_width      10
hide_window_decorations   yes

# Keybindinds
# map ctrl+c copy_to_clipboard
# map ctrl+v paste_from_clipboard


# Aesthetics
disable_ligatures         no
enable_audio_bell         no

background_opacity        0.85

